version: 2.1

orbs:
  orb-tools: circleci/orb-tools@7.3.0

workflows:
  lint_pack-validate_publish-dev:
    jobs:
      - orb-tools/lint
      - orb-tools/pack:
          requires:
            - orb-tools/lint
      - orb-tools/publish-dev:
          context: orb-publishing
          orb-name: timakin/go-module
          requires:
            - orb-tools/pack
      - orb-tools/trigger-integration-workflow:
          ssh-fingerprints: 95:0b:a2:cf:bd:98:4c:ab:0c:0f:0c:5a:f4:72:d1:bd
          requires:
            - orb-tools/publish-dev
          filters:
            branches:
              ignore: master
      - orb-tools/trigger-integration-workflow:
          ssh-fingerprints: 95:0b:a2:cf:bd:98:4c:ab:0c:0f:0c:5a:f4:72:d1:bd
          tag: master
          requires:
            - orb-tools/publish-dev
          filters:
            branches:
              only: master
